spring:
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:127.0.0.1}:8848 # nacos注册中心
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:your-namespace-uuid}
        group: DEFAULT_GROUP
        ip: ${APP_HOST:127.0.0.1}
      config:
        file-extension: yaml
  config:
    import:
      - nacos:shared-logs.yaml # 共享日志配置
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
      password: ${REDIS_PASSWORD:}
logging:
    com.agent: debug
jwt:
  public-key: ${JWT_PUBLIC_KEY:your-public-key-here}
