server:
  port: 18099  #服务端口
  host: 0.0.0.0 #监听所有网络接口
  logger:
    #    file: logs/app.log
    level: DEBUG # 日志级别: CRITICAL, ERROR, WARNING, INFO, DEBUG

nacos:
  server-addr: ${NACOS_HOST:127.0.0.1}:8848 # nacos注册中心
  username: ${NACOS_USERNAME:nacos}
  password: ${NACOS_PASSWORD:nacos}
  config:
    namespace: public
    group: DEFAULT_GROUP
  discovery:
    name: agent-center
    namespace: ${NACOS_NAMESPACE:your-namespace-uuid}
    ip: ${APP_HOST:127.0.0.1}